CREATE DATABASE A
USE A
CREATE TABLE Sliders 
(
Id INT PRIMARY KEY IDENTITY ,
Title NVARCHAR(500)NOT NULL,
Text NVARCHAR(500)NOT NULL,
Image NVARCHAR(100),
[Order] INT 

)
CREATE TABLE Catagories
(
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(30) NOT NULL 
)
CREATE TABLE Tags
(
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(30) 
)
CREATE TABLE Products
(
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(30)NOT NULL,
Price DECIMAL(18,2) NOT NULL,
CatagoryId INT CONSTRAINT CI_CHECK FOREIGN KEY REFERENCES Catagories(Id),
DiscountAmount DECIMAL(18,2)NOT NULL,
IsNew BIT NOT NULL,
[Count] INT ,
[Desc] NVARCHAR(1500)NOT NULL,
Code NVARCHAR(10)NOT NULL,
CostPrice DECIMAL(18,2)NOT NULL
)
CREATE TABLE ProductTags
(Id INT PRIMARY KEY IDENTITY,
ProductId INT CONSTRAINT PI_CHECK FOREIGN KEY REFERENCES Products(Id),
TagId INT CONSTRAINT  TI_CHECK FOREIGN KEY REFERENCES Tags(Id),

)
CREATE TABLE Users
(
Id INT PRIMARY KEY IDENTITY,
FullName NVARCHAR(35)NOT NULL,
Email NVARCHAR(100)NOT NULL,
Image NVARCHAR(100)NOT NULL,
PasswordHash NVARCHAR(100)NOT NULL,
Address NVARCHAR(100)NOT NULL
)
CREATE TABLE Reviews 
(
Id INT PRIMARY KEY IDENTITY,
ProductId  INT CONSTRAINT PC_CHECK FOREIGN KEY REFERENCES Products(Id),
UserId INT CONSTRAINT UI_check FOREIGN KEY REFERENCES Users(Id),
Name NVARCHAR(30)NOT NULL ,
Email NVARCHAR(100)NOT NULL,
Text NVARCHAR(350)NOT NULL,
CreatedAt DATETIME2 NOT NULL
)
CREATE TABLE Orders
(
Id INT PRIMARY KEY IDENTITY,
UserId INT CONSTRAINT UU_CHECK FOREIGN KEY REFERENCES Users(Id),
CreatedAt DATETIME2 NOT NULL,
DeliveriedAt DATETIME2 NOT NULL,
Status TINYINT NOT NULL,
PaymentStatus TINYINT NOT NULL,
TotalAmount DECIMAL(18,2)NOT NULL,
[Address] NVARCHAR(100)NOT NULL,
Email NVARCHAR(100)NOT NULL,
FullName NVARCHAR(35)NOT NULL

)
CREATE TABLE OrderItems
(
Id INT PRIMARY KEY IDENTITY,
ProductId INT CONSTRAINT PP_CHECK FOREIGN KEY REFERENCES Products(Id),
OrderId INT CONSTRAINT OR_CHECK FOREIGN KEY REFERENCES Orders(Id),
[Count] INT NOT NULL,
Price DECIMAL(18,2) NOT NULL,
DicountAmount DECIMAL(18,2)NOT NULL,
CostPrice DECIMAL(18,2)NOT NULL
)
CREATE TABLE ProductImages
(
Id INT PRIMARY KEY IDENTITY,
ProductId INT CONSTRAINT PD_CHECK FOREIGN KEY REFERENCES Products(Id),
Image NVARCHAR(100)NOT NULL
)
CREATE TABLE AdditionallFoTypes
(
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(30) NOT NULL
)
CREATE TABLE AdditionallFos
(
Id INT PRIMARY KEY IDENTITY ,
ProductId INT CONSTRAINT Pf_CHECK FOREIGN KEY REFERENCES Products(Id),
AdditionallFoTypeId INT CONSTRAINT AF_CHECK FOREIGN KEY REFERENCES AdditionallFoTypes(Id),
Value NVARCHAR(30)NOT NULL
)
